name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: corepack enable pnpm && pnpm i

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Website
        run: pnpm build

      - name: Checkout GitHub Pages Repo
        uses: actions/checkout@v3
        with:
          repository: flexilte/flexilte.github.io
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Build Content
        run: |
          cp -r apps/docs/build/* gh-pages/

      - name: Commit and Push Changes
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          touch .nojekyll
          git add .
          git commit -m "Update Website"
          git push
